### PR TITLE
feat: add `https://cgr.dev` to default Helm registries

### PR DESCRIPTION
**Pull request by onedr0p**
Adds chainguards container registry to default helm values

### CODE REVIEW

**Comment by phillebaba** [comment]
@onedr0p can you run `make helm-docs` to update the generated documentation, then we can merge this.

**Comment by onedr0p** [comment]
@phillebaba updated

**Comment by phillebaba** [comment]
Sorry i missed it, could you also add an entry to the changelog :)

**Comment by onedr0p** [comment]
@phillebaba updated

**Pull request merged**
